---
title: "Can human values explain one’s interest in cryptocurrencies? A correlational study in Germany"
author: 
  - name: "Adrian Stanciu"
    affiliation_number: 1
  - name: "Melanie Partsch"
    affiliation_number: 1
  - name: "Mariana Bernardes"
    affiliation_number: 2
  - name: "Ranjit Singh"
    affiliation_number: 1
  - name: "Clemens Lechner"
    affiliation_number: 1
affiliations:
  - "GESIS-Leibniz Institute for the Social Sciences, Mannheim"
  - "University of Bremen, Bremen"
shorttitle: "Values and cryptocurrencies"
authors_note: "For correspondence contact Dr. Adrian Stanciu, Data and Research on Society, GESIS-Leibniz Institute for the Social Sciences, PO Box 12215, 68072 Mannheim, Germany. Email: adrian.stanciu[at]gesis.org"
abstract: "Write abstract here"
keywords: "Values, Cryptocurrencies, Germany"
date: "`r format(Sys.time(), '%d. %B, %Y')`"
doctype: doc
header-includes:
  - \usepackage{subfig}
output: 
  pdf_document:
    template: "style/template.tex"
csl: style/apa.csl
bibliography: reference.bib
---


```{r setup, include=FALSE, results="asis"}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

r <- getOption("repos")
r["CRAN"] <-"https://cloud.r-project.org/"
options(repos=r)

## these are packages needed for these analyses
if (!require(tidyverse)) {
    install.packages("tidyverse")
    require(tidyverse)
}
if (!require(dplyr)) {
    install.packages("dplyr")
    require(dplyr)
}
if (!require(knitr)) {
    install.packages("knitr")
    require(knitr)
}
if (!require(wesanderson)) {
    install.packages("wesanderson")
    require(wesanderson)
}
if (!require(haven)) {
    install.packages("haven")
    require(haven)
}
if (!require(kableExtra)) {
    install.packages("kableExtra")
    require(kableExtra)
}
if (!require(DT)) {
    install.packages("DT")
    require(DT)
}
if (!require(Hmisc)) {
  install.packages("Hmisc")
  require(Hmisc)
}
if (!require(corrplot)) {
  install.packages("corrplot")
  require(corrplot)
}

# load packages
library("tidyverse")
library("dplyr")
library("knitr")
library("wesanderson")
library("haven")
library("kableExtra")
library("DT")
library("Hmisc")
library("corrplot")

# --- imports data
load("data/df.Rdata")
load("data/descriptives.Rdata")
load("data/pca.Rdata")

# --- imports source scripts
source("scripts/helper_functions.R")

# --- theme for plots
mytheme <- theme(axis.text.x = element_text(angle = 45, vjust = 0.9, hjust=1, size = 10),
                 panel.background = element_rect(fill="white", color = "grey50"),
                 panel.grid.major.y = element_line(color="grey90"),
                 axis.title.y = element_text(vjust= 0.5, hjust=1, angle = 90) )

```

# Introduction

Cryptocurrencies are digital money, and much more. The idea of cryptocurrency has developed recently, in 2009, when a person or a group of people known as Satoshi Nakamoto have launched a novel currency that was entirely digital and based on a chain of mathematical algorithms. Their vision was one in which the centralized financial system as we know it can one day be de-centralized in that financial transactions will be possible directly between involved parties. The idea was a simple one: by eliminating the role of banks and governmental bodies that secure trust in financial transactions, unnecessary taxes can be eliminated, people can have more control of their finances, as well as global barriers due to currency conversion might as well be abolished. This has since entered the public knowledge domain and is now known as Bitcoin. Several variations of it and a number of alternative cryptocurrencies later, and it is becoming increasingly clear that the topic is no longer in the under-ground of our society, but quite the contrary, it is here to stay.

This research sets to explore reasons why some people are interested in this new form of finance whereas other are against it, or they are skeptical. We focus on the role of human values as possible explanators and seek to understand associations with an interest in and motivation to invest in cryptocurrencies among the general German population. We look at the associations between human values in the Theory of Basic Values [@Schwartz2012] and varying cryptocurrency items as they were formulated in a recent survey by the OECD [@OECD2019]. Data for this study is a quota sample in line with the demographics of the German general population and was collected April 2022.

## Briefly on cryptocurrencies 

[input from Mariana]

## Human values

[input from Adrian]

## The present research

Whay should it matter if values inform people's interst in cryptocurrencies? Values are beliefs that guide action in people, and this holds across cultures and contexts. What makes values ultimately relevant is that they are culture-informed, have a developmental trajectory that is lifelong [refer here manuscript by Smallenbroek, Stanciu et al], while they can change due to specific life events such as entering parenthood [@Lonnqvistetal2018], but also due to drastic changes in society such as due to the Covid-19 Pandemic [@Danieletal2022]. Cryptocurrencies hold several similarities with other technological advancements such as the Internet and mobile phones. Compared to previous advancements however, the notion of cryptocurrencies is also in a way an economic and political statement [Mariana = do you have a citation for this?]. Though this technology is still in its onset phase, there are reasons to expect that it will impact people's financial independence and potentially people's dependencies on established monetary and governmental institutions [Mariana = do you have a citation for this?]. 

In other words, the concept of cryptocurrency is potentially going to shape in the future in currently unknown ways people's motivational goals. We speak of the future because we want to raise awareness that a new technology is now being adopted, in spite of groups of people being against it or disbelieving its mission. This is happening. Therefore, to begin understanding how this will shape our beliefs in the future, we reason that the pertinent first step is to explore what makes this technology possible from a social perspective. That is, why some people are interested, engaged with, and open for this form of finance, while others are not. 

This study explores the present topic and it does not test for causal mechanisms. The present hypotheses therefore have the role of  guiding our interpretations of findings, rather than informing claims about theory. 

We can think of two approaches to how human values contribute to a person's interest in cryptocurrencies. Please note that this is here meant in a general sense; it addresses both awareness and holding of cryptocurrencies as well as overall beliefs about the topic. First, we acknowledge the fact that cryptocurrencies are a new form of finance thus it is potentially linked with people's motivational goals of accepting or rejecting novelty in their life. The hypothesis is that values of openness to change will associate with a stronger interest in crypto-currencies (Hypothesis 1). 

Second, we acknowledge the primary goal of cryptocurrencies - that of creating a decentralized financial system - thus facilitating financial independence in people who otherwise are dependent on monetary institutions such as banks. We reason that this might be linked with people's motivational goal of self-enhancing themselves, striving for own financial wellbeing that is. The hypothesis is that values of self-enhancement will associate with a stronger interest in cryptocurrencies (Hypothesis 2).

# Method

## Participants

[input from Clemens and/or Melanie]

Overall there are **N = `r unique(sample$total_n)`** participants who have at least heard of cryptocurrencies. This is our sample for the study.

## Measurement

### Values

### A

## Aanalytical approach

# Results

## Descriptives

# Discussion

## Limitations and future research

# Conclusion

# References